import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import styled from 'styled-components';
import { Spinner } from '@chakra-ui/react';
import Slider from '../components/Slider';
import { RootState } from '../redux/store';
import { useTasks } from '../utils/api';
import Tasks from '../components/Tasks';
import Sort from '../components/Sort';

const Home: NextPage = () => {
  const { tasks, sortView } = useSelector((state: RootState) => state.app);
  const { isLoading, error } = useTasks();

  if (isLoading) {
    return (
      <StyledBox>
        <StyledSpinner />
      </StyledBox>
    );
  }

  if (error) {
    return (
      <StyledBox>
        <StyledError>
          oops something went wrong! please check your internet
        </StyledError>
      </StyledBox>
    );
  }

  return (
    <StyledContainer>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {tasks && (
        <>
          <StyledContainerSlider>
            <Slider />
          </StyledContainerSlider>

          <StyledTasksContainer>
            <Tasks />
            {sortView && <Sort />}
          </StyledTasksContainer>
        </>
      )}
    </StyledContainer>
  );
};

export default Home;

const StyledContainer = styled.div`
  padding: 5rem;
`;

const StyledContainerSlider = styled.div`
  display: flex;
  justify-content: flex-end;
`;

const StyledTasksContainer = styled.div`
  margin-top: 8rem;
  display: flex;
  justify-content: center;
  align-items: center;
  display: flex;
  align-items: flex-start;
`;

const StyledBox = styled.div`
  height: 70vh;
  display: flex;
  justify-content: center;
  align-items: center;

  & > div {
    font-size: 5rem;
  }
`;

const StyledSpinner = styled(Spinner)`
  width: 8rem;
  height: 8rem;
`;

const StyledError = styled.div``;
